### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by jesperweiland** [ksya/homeassistant_nefiteasy_climate#1]
Hi!

This is what happens when I start hass with the nefiteasy_climate code:
```
2018-02-20 21:29:23 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
    result = next(coro)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity_platform.py", line 260, in _async_add_entity
    yield from entity.async_update_ha_state()
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity.py", line 222, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/climate/__init__.py", line 502, in state_attributes
    supported_features = self.supported_features
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/climate/__init__.py", line 785, in supported_features
    raise NotImplementedError()
NotImplementedError
```

My config:

```
climate:
  platform: nefit_easy
  host: localhost
  port: 3000
  scan_interval: 60
```

The nefit easy http server is running on port localhost:3000

**Comment by ksya** [comment]
Please use https://github.com/marconfus/ha-nefit

**Comment by trizz** [comment]
I have the same error. The suggested replacement for this package doesn't work with a Docker based HomeAssistant setup, so that's not an alternative 😕
